### ISSUE TITLE
error running zeus create

### ISSUE THREAD

**Issue by 0v3rfl00w** [zepp-health/zeppos-forum#373]
### Discussed in https://github.com/orgs/zepp-health/discussions/372

<div type='discussions-op-text'>

<sup>Originally posted by **0v3rfl00w** October 10, 2024</sup>
The development environment is setup properly 
`(base) PS D:\coding\coding\zeppOS\test_3> zeus -v
node: v22.9.0

npm: v10.9.0

zeus: v1.6.0

zpm: v2.6.6
` 
but running  zeus create hello-world returns this error :
`(base) PS D:\coding\coding\zeppOS\test_3> zeus create hello-world
main.js create <projectName>

Named the <projectName> project and add to the current directory.

Base Options
  -h, --help     Display help information.                             [boolean]
  -v, --version  Display version number.                               [boolean]

TypeError: Cannot read properties of undefined (reading 'apply')
    at C:\Users\b94ai\AppData\Local\Yarn\Data\global\node_modules\@zeppos\zeus-cli\utils\tools.js:85:41
    at step (C:\Users\b94ai\AppData\Local\Yarn\Data\global\node_modules\@zeppos\zeus-cli\utils\tools.js:33:23)
    at Object.next (C:\Users\b94ai\AppData\Local\Yarn\Data\global\node_modules\@zeppos\zeus-cli\utils\tools.js:14:53)
    at C:\Users\b94ai\AppData\Local\Yarn\Data\global\node_modules\@zeppos\zeus-cli\utils\tools.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\b94ai\AppData\Local\Yarn\Data\global\node_modules\@zeppos\zeus-cli\utils\tools.js:4:12)
    at Object.handler (C:\Users\b94ai\AppData\Local\Yarn\Data\global\node_modules\@zeppos\zeus-cli\utils\tools.js:73:16)
    at C:\Users\b94ai\AppData\Local\Yarn\Data\global\node_modules\yargs\build\index.cjs:1:8993
    at j (C:\Users\b94ai\AppData\Local\Yarn\Data\global\node_modules\yargs\build\index.cjs:1:4956)
    at _.handleValidationAndGetResult (C:\Users\b94ai\AppData\Local\Yarn\Data\global\node_modules\yargs\build\index.cjs:1:8962)
`

how would you fix this 
i am on windows 11 x64</div>

**Comment by miljosh68** [comment]
I have a similar on MacOS. Was unable to create project. Here's a link to my post. 
https://github.com/orgs/zepp-health/discussions/544#discussion-10652044

If your issue is fixed, please inform me. I'll do the same if mine gets answered before yours.

**Comment by miljosh68** [comment]
I was able to fix my issue with some help from AI. Please go through my post linked below. 
https://github.com/orgs/zepp-health/discussions/544#discussion-10652044

Hope you are able to fix it too.
